version: '3.7'

services:

  server:
    build: server/.
    volumes:
      - ./server/:/app
    ports:
      - 3000

  tsung:
    image: prima/tsung:1.6
    ports:
      - 8091:8091
    depends_on:
      - server
    volumes:
      - ./tsung/http_simple.xml:/root/.tsung/tsung.xml
      - ./tsung/log:/root/.tsung/log

  prometheus:
    image: prom/prometheus:v2.17.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 4000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/env

volumes:
  grafana_data:
  prometheus_data: