apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: false